#!/bin/bash
# Vibe Coding Terminal - Deployment Script
# Run this script on your Linux server to deploy the application

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=========================================="
echo "  Vibe Coding Terminal - Deployment"
echo "=========================================="
echo ""

# Check prerequisites
check_prerequisites() {
    echo "Checking prerequisites..."

    if ! command -v docker &> /dev/null; then
        echo "ERROR: Docker is not installed. Please install Docker first."
        echo "  curl -fsSL https://get.docker.com | sh"
        exit 1
    fi

    if ! docker compose version &> /dev/null; then
        echo "ERROR: Docker Compose is not available."
        exit 1
    fi

    echo "✓ Docker and Docker Compose are installed"
    echo ""
}

# Fix Docker socket path for Linux
fix_docker_socket() {
    if grep -q "//var/run/docker.sock" docker-compose.yml; then
        echo "Fixing Docker socket path for Linux..."
        sed -i 's|//var/run/docker.sock|/var/run/docker.sock|g' docker-compose.yml
        echo "✓ Docker socket path fixed"
    else
        echo "✓ Docker socket path already configured for Linux"
    fi
    echo ""
}

# Configure environment
configure_env() {
    if [ -f .env ]; then
        echo "Found existing .env file."
        read -p "Do you want to reconfigure? (y/N): " reconfigure
        if [[ ! "$reconfigure" =~ ^[Yy]$ ]]; then
            echo "Using existing configuration."
            return
        fi
    fi

    echo "Configuring environment variables..."
    echo ""

    # Domain
    read -p "Enter your domain (e.g., codepilot.example.com): " DOMAIN

    # Email
    read -p "Enter your email (for Let's Encrypt notifications): " EMAIL

    # GitHub OAuth
    echo ""
    echo "Create a GitHub OAuth App at: https://github.com/settings/developers"
    echo "  - Homepage URL: https://${DOMAIN}:7443"
    echo "  - Callback URL: https://${DOMAIN}:7443/oauth2/callback"
    echo ""
    read -p "Enter GitHub Client ID: " GITHUB_CLIENT_ID
    read -p "Enter GitHub Client Secret: " GITHUB_CLIENT_SECRET

    # Generate cookie secret
    COOKIE_SECRET=$(openssl rand -base64 32 | tr -- '+/' '-_')

    # Optional: Restrict access
    echo ""
    read -p "Restrict to specific GitHub users? (comma-separated, or leave empty): " GITHUB_ALLOWED_USERS
    read -p "Restrict to GitHub organization? (or leave empty): " GITHUB_ALLOWED_ORG

    # Write .env file
    cat > .env << EOF
# Vibe Coding Terminal - Environment Variables
# Generated by deploy.sh on $(date)

# Required Configuration
DOMAIN=${DOMAIN}
EMAIL=${EMAIL}
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
OAUTH2_PROXY_COOKIE_SECRET=${COOKIE_SECRET}
EOF

    # Add optional configurations
    if [ -n "$GITHUB_ALLOWED_USERS" ]; then
        echo "GITHUB_ALLOWED_USERS=${GITHUB_ALLOWED_USERS}" >> .env
    fi

    if [ -n "$GITHUB_ALLOWED_ORG" ]; then
        echo "GITHUB_ALLOWED_ORG=${GITHUB_ALLOWED_ORG}" >> .env
    fi

    echo ""
    echo "✓ Environment configured"
    echo ""
}

# Deploy
deploy() {
    echo "Deploying Vibe Coding Terminal..."
    echo ""

    # Pull images
    echo "Pulling latest images..."
    docker compose pull

    # Build code-server
    echo "Building code-server image..."
    docker compose build

    # Start services
    echo "Starting services..."
    docker compose up -d

    echo ""
    echo "✓ Deployment complete!"
    echo ""
}

# Show status
show_status() {
    echo "=========================================="
    echo "  Deployment Status"
    echo "=========================================="
    echo ""
    docker compose ps
    echo ""

    # Load domain from .env
    if [ -f .env ]; then
        source .env
        echo "Access your terminal at: https://${DOMAIN}:7443"
        echo ""
        echo "Troubleshooting:"
        echo "  - View logs: docker compose logs -f"
        echo "  - Restart:   docker compose restart"
        echo "  - Stop:      docker compose down"
    fi
}

# Main
main() {
    check_prerequisites
    fix_docker_socket
    configure_env
    deploy
    show_status
}

# Run with option to skip interactive config
if [ "$1" == "--status" ]; then
    show_status
elif [ "$1" == "--restart" ]; then
    docker compose restart
    show_status
elif [ "$1" == "--stop" ]; then
    docker compose down
elif [ "$1" == "--logs" ]; then
    docker compose logs -f
else
    main
fi
